version: '3.8'
services:
  compose-mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank

  compose-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    entrypoint: ["/app/wait-for-it.sh","compose-mysql:3306","--","/app/start.sh"]
    command: ["/app/main"]
